//! Example 3: a fixed-point electric-guitar reverb pedal.
//!
//! A transaction-level DSP model that streams blocks of audio samples through a
//! reverb (a feedback comb filter for the echo train + a Schroeder allpass for
//! diffusion) with an optional tremolo, all in **bit-accurate fixed point**. It
//! showcases three things at once:
//!
//! - **Bring-your-own datatypes.** SystemRS deliberately drops SystemC's `sc_dt`
//!   (design §3.12); a model brings idiomatic Rust types and the generic payload
//!   carries their bytes. Here the samples are [`qfixed`]'s TI-style `Q2.14`
//!   (`Q<U2, U14>`), and the tremolo LFO is generated by a **complex** `CQ<U2, U14>`
//!   numerically-controlled oscillator (an IQ phasor rotated by a complex multiply
//!   each sample) — exactly the kind of fixed-point IQ datapath a radio or audio
//!   twin needs.
//! - **Streaming over TLM with temporal decoupling.** The pedal is a target socket;
//!   an initiator `b_transport`s one block of samples per transaction, processed in
//!   place, advancing simulation time by the block duration (a quantum of audio).
//! - **Non-intrusive observability.** Each block's peak output level is broadcast on
//!   an [`AnalysisPort`], so a meter/scoreboard can watch the signal without
//!   perturbing it.
//!
//! All arithmetic uses `qfixed`'s `saturating_*` operators, which clamp at the format
//! limits rather than wrapping — the honest behaviour of a fixed-width DSP register.

use std::cell::RefCell;
use std::rc::Rc;

use qfixed::typenum::{U2, U14};
use qfixed::{CQ, Q};
use systemrs::prelude::*;

/// The audio sample format: TI `Q2.14` — 1 sign bit, 1 integer bit, 14 fractional
/// bits, range `[-2, 2)`. (Q1.15 is the more common audio format; Q2.14 trades one
/// fractional bit for the headroom to represent `1.0` and brief feedback overshoot.)
type Sample = Q<U2, U14>;

/// The complex sample format for the IQ tremolo oscillator.
type Phasor = CQ<U2, U14>;

/// Bytes per packed sample on the wire (`Q2.14` is 16 bits).
const SAMPLE_BYTES: usize = 2;

/// Packs a sample into its little-endian 16-bit two's-complement wire form.
fn pack(s: Sample) -> [u8; SAMPLE_BYTES] {
    let bytes = s.to_bits().to_le_bytes(); // low 16 bits hold the value
    [bytes[0], bytes[1]]
}

/// Unpacks a sample from its little-endian 16-bit wire form.
fn unpack(lo: u8, hi: u8) -> Sample {
    Sample::from_bits(u64::from(u16::from_le_bytes([lo, hi])))
}

/// A feedback comb filter: `y[n] = x[n] + g·y[n-D]` — a decaying echo train.
struct Comb {
    /// Delay line of length `D`, holding past outputs.
    buf: Vec<Sample>,

    /// Write/read cursor.
    pos: usize,

    /// Feedback gain `g` (magnitude `< 1` for a decaying, stable response).
    gain: Sample,
}

impl Comb {
    /// Creates a comb with delay `d` samples and feedback `gain`.
    fn new(d: usize, gain: Sample) -> Self {
        Comb {
            buf: vec![Sample::ZERO; d.max(1)],
            pos: 0,
            gain,
        }
    }

    /// Processes one sample.
    fn process(&mut self, x: Sample) -> Sample {
        let delayed = self.buf[self.pos];
        let y = x.saturating_add(delayed.saturating_mul(self.gain));
        self.buf[self.pos] = y;
        self.pos = (self.pos + 1) % self.buf.len();
        y
    }
}

/// A Schroeder allpass filter: flattens the magnitude response while diffusing the
/// echoes, giving the reverb density without colouration.
struct Allpass {
    /// Delay line of length `D`.
    buf: Vec<Sample>,

    /// Write/read cursor.
    pos: usize,

    /// Diffusion coefficient `g`.
    gain: Sample,
}

impl Allpass {
    /// Creates an allpass with delay `d` samples and coefficient `gain`.
    fn new(d: usize, gain: Sample) -> Self {
        Allpass {
            buf: vec![Sample::ZERO; d.max(1)],
            pos: 0,
            gain,
        }
    }

    /// Processes one sample.
    fn process(&mut self, x: Sample) -> Sample {
        let v_delayed = self.buf[self.pos];
        let v = x.saturating_add(v_delayed.saturating_mul(self.gain));
        let y = v_delayed.saturating_sub(v.saturating_mul(self.gain));
        self.buf[self.pos] = v;
        self.pos = (self.pos + 1) % self.buf.len();
        y
    }
}

/// A numerically-controlled oscillator for the tremolo LFO, built on a **complex**
/// `Q2.14` phasor: each step rotates the unit phasor by a fixed angle via one complex
/// multiply, and the real part is the cosine LFO. This is the IQ datapath — the same
/// shape an RF mixer or quadrature synthesizer uses.
///
/// The fixed-point rotation drifts in magnitude very slowly (rounding); a production
/// NCO would renormalize each step (see [`CQ::norm_sqr`]). Over a short modulation
/// run the drift is negligible.
struct Nco {
    /// The current unit phasor (`re` is the cosine LFO).
    phasor: Phasor,

    /// The per-sample rotation `exp(i·ω)`.
    step: Phasor,

    /// Tremolo gain offset, `1 − depth/2`.
    bias: Sample,

    /// Tremolo modulation amplitude, `depth/2`.
    amp: Sample,
}

impl Nco {
    /// Creates an LFO at `freq_norm` cycles/sample with tremolo `depth` in `[0, 1]`.
    fn new(freq_norm: f64, depth: f64) -> Self {
        let w = core::f64::consts::TAU * freq_norm;
        Nco {
            phasor: Phasor::from_f64(1.0, 0.0),
            step: Phasor::from_f64(w.cos(), w.sin()),
            bias: Sample::from_f64(1.0 - depth * 0.5),
            amp: Sample::from_f64(depth * 0.5),
        }
    }

    /// Advances the phasor and returns the next tremolo gain in `[1−depth, 1]`.
    fn next_gain(&mut self) -> Sample {
        self.phasor = self.phasor.saturating_mul(self.step); // complex rotation
        self.bias
            .saturating_add(self.amp.saturating_mul(self.phasor.re))
    }
}

/// Configuration for a [`Reverb`].
#[derive(Clone, Copy)]
pub struct ReverbParams {
    /// Comb delay in samples.
    pub comb_delay: usize,

    /// Comb feedback gain (`0.0..1.0`).
    pub comb_gain: f64,

    /// Allpass delay in samples.
    pub allpass_delay: usize,

    /// Allpass diffusion coefficient (`0.0..1.0`).
    pub allpass_gain: f64,

    /// Tremolo LFO frequency in cycles per sample.
    pub lfo_freq_norm: f64,

    /// Tremolo depth (`0.0` = off, `1.0` = full).
    pub depth: f64,
}

impl Default for ReverbParams {
    fn default() -> Self {
        ReverbParams {
            comb_delay: 1500,
            comb_gain: 0.7,
            allpass_delay: 225,
            allpass_gain: 0.5,
            lfo_freq_norm: 0.0007,
            depth: 0.0,
        }
    }
}

/// The reverb DSP graph: a feedback comb → a diffusing allpass → tremolo.
pub struct Reverb {
    /// The echo-train comb.
    comb: Comb,

    /// The diffusing allpass.
    allpass: Allpass,

    /// The tremolo LFO.
    nco: Nco,
}

impl Reverb {
    /// Builds a reverb from `params`.
    ///
    /// # Arguments
    ///
    /// * `params` - The filter and tremolo configuration.
    ///
    /// # Returns
    ///
    /// A fresh [`Reverb`] with cleared delay lines.
    pub fn new(params: ReverbParams) -> Self {
        Reverb {
            comb: Comb::new(params.comb_delay, Sample::from_f64(params.comb_gain)),
            allpass: Allpass::new(params.allpass_delay, Sample::from_f64(params.allpass_gain)),
            nco: Nco::new(params.lfo_freq_norm, params.depth),
        }
    }

    /// Processes one sample through the full graph.
    ///
    /// # Arguments
    ///
    /// * `x` - The input sample.
    ///
    /// # Returns
    ///
    /// The processed output sample.
    // ANCHOR: process
    pub fn process_sample(&mut self, x: Sample) -> Sample {
        let echoed = self.comb.process(x);
        let diffused = self.allpass.process(echoed);
        diffused.saturating_mul(self.nco.next_gain())
    }
    // ANCHOR_END: process
}

/// A TLM reverb pedal: a target socket that processes one block of `Q2.14` samples
/// per `b_transport`, in place, and broadcasts each block's peak output level.
pub struct ReverbPedal {
    /// Per-block peak output level (raw `Q2.14` count), for a meter/scoreboard.
    level: Rc<AnalysisPort<i64>>,
}

impl ReverbPedal {
    /// Connects a reverb pedal as the `b_transport` target of `target`.
    ///
    /// # Arguments
    ///
    /// * `sim` - The simulation under construction.
    /// * `target` - The target socket to service.
    /// * `params` - The reverb configuration.
    ///
    /// # Returns
    ///
    /// The [`ReverbPedal`]; bind a subscriber to [`ReverbPedal::level_port`] to meter
    /// the output.
    pub fn connect(sim: &Sim, target: &TargetSocket, params: ReverbParams) -> ReverbPedal {
        let dsp = Rc::new(RefCell::new(Reverb::new(params)));
        let level = Rc::new(AnalysisPort::<i64>::new());
        let meter = Rc::clone(&level);
        target.register_b_transport(sim, move |_cx, payload, _delay| {
            let mut dsp = dsp.borrow_mut();
            let mut peak: i64 = 0;
            for frame in payload.data_mut().chunks_exact_mut(SAMPLE_BYTES) {
                let y = dsp.process_sample(unpack(frame[0], frame[1]));
                let bytes = pack(y);
                frame[0] = bytes[0];
                frame[1] = bytes[1];
                peak = peak.max(y.to_count().abs());
            }
            payload.set_response_status(ResponseStatus::Ok);
            meter.write(&peak); // broadcast the block's peak (non-intrusive)
        });
        ReverbPedal { level }
    }

    /// Returns the per-block peak-level analysis port (bind a meter/scoreboard here).
    pub fn level_port(&self) -> Rc<AnalysisPort<i64>> {
        Rc::clone(&self.level)
    }
}

/// Packs a block of `f64` samples (in `[-2, 2)`) into a `Q2.14` little-endian byte
/// buffer suitable for a [`GenericPayload`].
///
/// # Arguments
///
/// * `samples` - The samples to quantize and pack.
///
/// # Returns
///
/// The packed bytes (`2` per sample).
pub fn pack_block(samples: &[f64]) -> Vec<u8> {
    let mut out = Vec::with_capacity(samples.len() * SAMPLE_BYTES);
    for &s in samples {
        out.extend_from_slice(&pack(Sample::from_f64(s)));
    }
    out
}

/// Unpacks a `Q2.14` little-endian byte buffer back into `f64` samples.
///
/// # Arguments
///
/// * `bytes` - The packed buffer (`2` bytes per sample).
///
/// # Returns
///
/// The samples as `f64`.
pub fn unpack_block(bytes: &[u8]) -> Vec<f64> {
    bytes
        .chunks_exact(SAMPLE_BYTES)
        .map(|c| unpack(c[0], c[1]).to_f64())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::{Comb, Nco, ReverbParams, ReverbPedal, Sample, pack_block, unpack_block};
    use std::cell::RefCell;
    use std::rc::Rc;
    use systemrs::prelude::*;

    /// The comb produces a geometric echo train: an impulse re-appears at each delay
    /// `D`, scaled by the feedback gain.
    #[test]
    fn comb_echoes_decay_geometrically() {
        let d = 4;
        let g = 0.7;
        let mut comb = Comb::new(d, Sample::from_f64(g));

        let mut out = Vec::new();
        out.push(comb.process(Sample::from_f64(0.5)).to_f64()); // impulse
        for _ in 0..(3 * d) {
            out.push(comb.process(Sample::ZERO).to_f64());
        }

        assert!((out[0] - 0.5).abs() < 0.01, "dry sample passes through");
        assert!((out[d] - 0.5 * g).abs() < 0.01, "first echo at D");
        assert!((out[2 * d] - 0.5 * g * g).abs() < 0.01, "second echo at 2D");
    }

    /// The complex NCO produces a bounded cosine: its real part swings positive and
    /// negative over a period.
    #[test]
    fn nco_oscillates() {
        let mut nco = Nco::new(0.02, 1.0); // ~50 samples/cycle, full depth
        let mut min = f64::MAX;
        let mut max = f64::MIN;
        for _ in 0..200 {
            // gain = 0.5 + 0.5*cos ranges over [0, 1].
            let g = nco.next_gain().to_f64();
            min = min.min(g);
            max = max.max(g);
        }
        assert!(max > 0.8, "LFO reaches its peak ({max})");
        assert!(min < 0.2, "LFO reaches its trough ({min})");
    }

    /// `Q2.14` round-trips through the byte packing within one quantization step.
    #[test]
    fn pack_round_trips() {
        let input = [0.0, 0.5, -0.5, 1.0, -1.25];
        let back = unpack_block(&pack_block(&input));
        for (a, b) in input.iter().zip(back.iter()) {
            assert!((a - b).abs() < 1.0 / 16384.0 + 1e-9, "{a} vs {b}");
        }
    }

    /// End-to-end over TLM: an initiator streams an impulse block then silent blocks
    /// to the pedal; the output develops a decaying reverb tail and the level port
    /// reports it.
    #[test]
    fn pedal_streams_and_meters_a_reverb_tail() {
        let sim = Sim::new();
        let target = TargetSocket::new(&sim, "pedal");
        let params = ReverbParams {
            comb_delay: 8,
            allpass_delay: 3,
            depth: 0.0, // tremolo off so the tail is purely the comb/allpass
            ..ReverbParams::default()
        };
        let pedal = ReverbPedal::connect(&sim, &target, params);

        // Meter: collect each block's peak level via the analysis port.
        let peaks: Rc<RefCell<Vec<i64>>> = Rc::new(RefCell::new(Vec::new()));
        struct Meter(Rc<RefCell<Vec<i64>>>);
        impl AnalysisWrite<i64> for Meter {
            fn write(&self, p: &i64) {
                self.0.borrow_mut().push(*p);
            }
        }
        let meter = Rc::new(Meter(Rc::clone(&peaks)));
        pedal.level_port().bind(&meter);

        let isock = InitiatorSocket::new(&sim, "guitar");
        isock.bind(&sim, &target);
        let tails: Rc<RefCell<Vec<Vec<f64>>>> = Rc::new(RefCell::new(Vec::new()));
        let collected = Rc::clone(&tails);
        sim.add_method("guitar", &[], true, move |cx| {
            // Block 0: an impulse; blocks 1..4: silence — the tail must persist.
            for block in 0..4 {
                let mut samples = vec![0.0f64; 16];
                if block == 0 {
                    samples[0] = 0.5;
                }
                let mut payload = GenericPayload::write(0, pack_block(&samples));
                let mut delay = SimTime::ZERO;
                isock.b_transport(cx, &mut payload, &mut delay);
                collected.borrow_mut().push(unpack_block(payload.data()));
            }
        });

        sim.run_until(SimTime::from_us(10));

        let tails = tails.borrow();
        let energy = |b: usize| -> f64 { tails[b].iter().map(|s| s.abs()).sum() };
        // The impulse produced output in block 0…
        assert!(energy(0) > 0.1, "the impulse produced output");
        // …a later, silent-input block still carries reverberant energy (the comb's
        // feedback delay carried the echo train forward)…
        assert!(
            energy(3) > 0.0,
            "the reverb tail persists into silent blocks"
        );
        // …and that tail decays over time.
        assert!(energy(1) > energy(3), "the tail decays");
        // The meter saw one peak per block, all four.
        assert_eq!(peaks.borrow().len(), 4);
    }
}
